classDiagram

    Product <|--Ticket
    Product <|--Publication
    Publication <|-- Book
    Publication <|-- Magazine
    Magazine <|-- DiscMag
    SaleableItem <|.. Product
    Serializable <|.. Product
    Cart "0..*" --> "0..*" Product : contains


    class Product{
        -Long id
        -String productId
        -double price
        -int copies
    }

    class Serializable{
        <<interface>>
    }

    class Cart{
        -Long id
        -List items
        +addItem(Product item)
        +getItems()
        +setItems(List items)
    }


    class Publication{
        <<Abstract>>
        -String title
        -double price
        -int copies
        +getPrice()

        +Publication()
        +Publication(String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()

    }
    class Book{
        -String isbn
        -String author

        +Book()
        +Book(String author)
        +Book(String author, String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()

    }
    class Magazine{
        -int orderQty
        -LocalDateTime currentIssue

        +Magazine()
        +Magazine(int orderQty, Date currentIssue, String title, double price, int copies)

        +sellItem()
    }
    class DiscMag{
        -boolean hasDisc
        +sellItem()

        +DiscMag()
        +DiscMag(boolean, hasDisc, int orderQty, Date currentIssue, String title, double price, int copies)

    }

    class SaleableItem {
        <<interface>>
        +sellItem()
        +getPrice()

    }

    class Ticket {
    -String description
    -double price
    -String type
    }